# Generated by Django 5.1.3 on 2025-01-27 18:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0002_cart_cartitem_contact"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("new", "NEW"),
                    ("processing", "PROCESSING"),
                    ("completed", "COMPLETED"),
                    ("canceled", "CANCELED"),
                ],
                default="new",
                max_length=20,
                verbose_name="Статус",
            ),
        ),
    ]
