# Generated by Django 5.1.3 on 2025-01-28 17:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_alter_customuser_role"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="google_id",
            field=models.CharField(
                blank=True,
                max_length=50,
                null=True,
                unique=True,
                verbose_name="Google ID",
            ),
        ),
        migrations.AddField(
            model_name="customuser",
            name="google_profile_picture",
            field=models.URLField(
                blank=True, null=True, verbose_name="Фото профиля Google"
            ),
        ),
    ]
